
create table core.users (
  id uuid primary key default uuid_generate_v4(),
  email citext not null unique,
  password_hash text not null,                       -- argon2/bcrypt hash generated by backend
  full_name varchar(255),
  phone varchar(50),
  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- user belongs to one or more schools
create table core.user_tenants (
  id uuid primary key default uuid_generate_v4(),
  tenant_id uuid not null references core.tenants(id) on delete cascade,
  user_id uuid not null references core.users(id) on delete cascade,
  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  unique (tenant_id, user_id)
);

-- refresh sessions (backend-controlled)
create table core.auth_sessions (
  id uuid primary key default uuid_generate_v4(),
  tenant_id uuid not null references core.tenants(id) on delete cascade,
  user_id uuid not null references core.users(id) on delete cascade,

  refresh_token_hash text not null,                  -- store hash, never store raw token
  revoked_at timestamptz,
  expires_at timestamptz not null,

  created_at timestamptz not null default now(),
  last_used_at timestamptz
);

create index on core.user_tenants (tenant_id, user_id);
create index on core.auth_sessions (tenant_id, user_id);
create index on core.auth_sessions (expires_at);
