-- 009_seed_permissions.sql
-- Paste finalized SQL here.
insert into core.permissions (code, description) values
('tenant.profile.read', 'Read tenant profile/settings'),
('tenant.profile.update', 'Update tenant profile/settings'),
('iam.users.read', 'Read users'),
('iam.users.create', 'Create users'),
('iam.users.update', 'Update users'),
('iam.users.disable', 'Disable users'),
('iam.roles.manage', 'Manage roles & permissions'),
('students.profile.read', 'Read student profile'),
('students.profile.create', 'Create student'),
('students.profile.update', 'Update student'),
('students.profile.archive', 'Archive student'),
('students.photo.upload', 'Upload student photo'),
('parents.profile.read', 'Read parent profile'),
('parents.profile.update', 'Update parent profile'),
('staff.profile.read', 'Read staff profile'),
('staff.profile.create', 'Create staff profile'),
('staff.profile.update', 'Update staff profile'),
('structure.read', 'Read school structure'),
('structure.manage', 'Manage school structure'),
('enrollment.read', 'Read enrollments'),
('enrollment.manage', 'Manage enrollments'),
('attendance.read', 'Read attendance'),
('attendance.mark', 'Mark attendance'),
('attendance.edit', 'Edit attendance'),
('academics.assessments.read', 'Read assessments'),
('academics.assessments.manage', 'Manage assessments'),
('academics.results.read', 'Read results'),
('academics.results.edit', 'Edit results'),
('academics.reports.publish', 'Publish reports'),
('fees.invoice.read', 'Read invoices'),
('fees.invoice.issue', 'Issue invoices'),
('fees.payment.record', 'Record payments'),
('fees.receipt.issue', 'Issue receipts'),
('fees.receipt.void.request', 'Request receipt void'),
('fees.receipt.void.approve', 'Approve receipt void'),
('fees.receipt.void.execute', 'Execute receipt void'),

('audit.read', 'Read audit log')
on conflict (code) do nothing;
